server:
    port: 9097

jedis :
  pool :
    host : 192.168.0.230
#    host : 192.168.12.4
    port : 6379
    database: 1
    password: ""
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000

spring:
  rabbitmq:
      host: 192.168.0.175
      port: 5672
      username: java
      password: sdgl#123
  data:
        #开发环境配置
          mongodb: # 配置mongoDB
              database: API
              uri: mongodb://192.168.30.100:27017
#              host:
#              port: 36918
#              database: NTFoxERP
#              username: jjkj
#              password: jjkj#123!!!
          elasticsearch:
              #cluster-name: #默认为elasticsearch
              cluster-nodes: 192.168.0.230:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
              cluster-name: docker-cluster
              properties:
                  path:
                    logs: ./elasticsearch/log #elasticsearch日志存储目录
                    data: ./elasticsearch/data #elasticsearch数据存储目录

sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:sqlserver://192.168.0.232:1433;DatabaseName=ERP
        username: sa
        password: abc,,,123
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:sqlserver://192.168.0.232:1433;DatabaseName=ERP
        username: sa
        password: abc,,,123
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    config:
        masterslave:
          load-balance-algorithm-type: round_robin
          name: ms
          master-data-source-name: ds0
          slave-data-source-names: ds1
          props:
            sql:
              show:
                true


webHome: "http://h5s.aipinzan.cn/#/home"

site: "上海站"
siteid: "10935D1F-8B33-993F-F242-27437BDA95D3"

#线路类型
JWrouteTypeId: "609380AD-14F2-478A-901B-7BC289CDB421"
CXrouteTypeId: "4A9E2935-0940-40E7-A742-64BEB2174F1B"
DXrouteTypeId: "F10AFF04-8652-444B-BC1B-418DDAC79F57"

#.netapi接口
airPortUrl:
      #机场三字码转换获取接口
      url: "http://192.168.30.102:8765/api/AirPort/TakeAirPortCache?key="
      #旅行社注册信息获取接口
      getOrgInfoUrl: "http://192.168.30.102:8765/api/OrgInfo/GetOrgInfoExtension?orgID="
      #绑定ERP用户openid接口
      BindUserOpenID_H5Shop: "http://192.168.30.102:8765/api/User/BindUserOpenID_H5Shop"
      #检查登录用户是否为ERP用户
      ExistWeChatOpenID: "http://192.168.30.102:8765/api/User/ExistWeChatOpenID_H5Shop?OpenID="
      #查询用户登录信息
      userAccountID: "http://192.168.30.102:8765/api/User/GetAcct?userAccountID="
      #查询直客是否注册
      H5_UserLogin: "http://192.168.30.102:8765/api/H5UserIdentification/H5_UserLogin?loginType=%s&loginIdentifier=%s"
      #直客注册
      H5_Save: "http://192.168.30.102:8765/api/H5UserIdentification/H5_Save"
      #new直客注册
      NewH5_Save: "http://192.168.30.102:8765/api/H5UserIdentification/NewH5_Save"
      #new获取用户信息
      getNewH5ShopUserId: "http://192.168.30.102:8765/api/H5SpecialShop/getNewH5ShopUserId"
      #获取H5用户信息
      H5_GetUserInfo: "http://192.168.30.102:8765/api/H5UserIdentification/H5_GetUserInfo?userId="
      #获取用户的相关信息url
      userInfoURL: "http://192.168.30.102:8765/api/UserIdentification/GetUserInfo?userID="
      #定制游订单提交成功后post接口
      cusInfoMatch: "http://192.168.30.102:8765/api/CusInfo/CusInfoMatch?cusInfoId="
      #定制游需求单POST接口
      addCusInfoByWeb: "http://192.168.30.102:8765/api/CusInfo/AddCusInfoByWeb"
      #生成占位订单
      GetGeneratePlaceholder: "http://192.168.30.102:8765/api/OrdOrderInfo/GetGeneratePlaceholder?orderId="
      #获得机场名称
      getAirPortName: "http://192.168.30.102:8765/api/AirPort/TakeAirPortCache?key="
      #用户详情接口
      getUserUrl: "http://192.168.30.102:8765/api/User/Get?userID="
      #获取邀请码
      getUserInvitation: "http://192.168.30.102:8765/api/User/GetUserInvitation?userID="
      #获得用户账号信息
      getAdminInfo: "http://192.168.30.102:8765/api/User/GetAdminInfo?orgID="
      #获得旅行社信息
      getSupplierNameByID: "http://192.168.30.102:8765/api/OrgInfo/GetSupplierNameByID?ids="
      #Dept
      getDept: "http://192.168.30.102:8765/api/Dept/Get?keyID="
      #获得用户详情
      getAcct: "http://192.168.30.102:8765/api/User/GetAcct?userAccountID="
      #志愿者店铺短信通知
      sendOrderPaySMS: "http://192.168.30.102:8765/api/OrdOrderInfo/SendOrderPaySMS"
      #失信人
      dishonestPeople: "http://192.168.30.100:9093/searchDishonestPeople?orderId="
      # 发送消息(ProIdsAndUserIdAndOrgId)都Mq 志愿者
      sendVolPro: "http://192.168.30.100:9096/sendMqPro"
      #一键铺货的时候 发送消息(B端主动分销数据同步 by orgId)
      sendDirectProByOrgId: "http://192.168.30.100:9096/addDirectProByOrgId?orgId="
      #一键铺货的时候 发送消息(B端主动分销数据同步 by proId)
      sendDirectProByProId: "http://192.168.30.100:9096/addDirectProByProId?proId="
      #订单wx模板消息通知
      sendTemplateMsg: "http://192.168.30.100:9096/sendOrderTemplateMessage"
#图片保存路径
imgPath: /usr/local/nginx/html/h5/file/
imgUrl: http://h5s.aipinzan.cn/file/
#商城首页
h5Url: "http://h5s01.aipinzan.cn/"

#志愿者--本地调试：
Volunteer:
  #身份证图片
  UserCardPath: E:\apache-tomcat-8.0.50\webapps\ROOT\file\UserCard\
  #店铺头像图片
  ShopHeadPath: E:\apache-tomcat-8.0.50\webapps\ROOT\file\ShopHead\
  #下载路径 身份证
  UserCardDownload: http://192.168.0.152:8123/file/UserCard/
  #下载路径 店铺头像
  ShopHeadDownload: http://192.168.0.152:8123/file/ShopHead/
  #二维码
  ImgPath: E:\apache-tomcat-8.0.50\webapps\ROOT\file\Volunteer\
  #二维码获取路径
  ImgUrl: http://192.168.0.152:8123/file/Volunteer/

wechat:
  appid: "wx53f70e7952c20d87"
  secret: cbade601c1f71d5dd21417214ec81866
  encodingAesKey: "3E015gANAOLTyQINrYurYcXZe4HdJ3nGCaPQnKeb09p"
  pay:
    appId: wxd6a4420ed7485e80
    mchId: 1352023001
    mchKey: "jingjie123456AaAjingjie123456AaA"
    keyPath: "classpath:/static/apiclient_cert.p12"
devStatus: "zc"
payNotify: http://h5s01.aipinzan.cn/Pay/PayAPI/payNotify
#竞界微信公众号的配置对应的orgID
jjkjOrgId: 00000000-0000-0000-0000-000000000001

#logging:
#  level:
#    com.holyrobot: DEBUG

lvyLogo: http://h5s.laolvyou.vip/file/icon/de-logo.png